Completed Sprint task and renamed all "Register" items to "SignUp"
ctc-uci/aiss-frontend pull request #16
Opened 2024-01-16 07:29 UTC by h0ethan04

Added frontend routes to App.jsx; created new pages for Playground, Published Schedule and Catalog. 
Changed login path to` '/login'` from `'/'` and renamed all items and files from "Register" to "SignUp" to better fit design plans.
closes #13

2024-01-18 20:27 UTC, michellelin1 requested changes, later dismissed
thanks for getting your PR in early! Everything looks good, just a few minor changes: change the redirect path to `/login` and add back the `/` route for PublishedSchedule page (you can still leave `/publishedSchedule` for now). Once those are addressed, this PR should be good :)

2024-01-18 20:27 UTC, michellelin1 commented on src/App.jsx
> +                    redirectPath="/"
could you change the redirectPath to `/login` for all the protected routes?

2024-01-18 20:27 UTC, michellelin1 commented on src/App.jsx
> -              <Route exact path="/" element={<Login />} />
we still want the `/` path, could that load the `PublishedSchedule` page?

2024-01-21 23:36 UTC, ThatMegamind submitted a review, later dismissed
Thanks for making those changes, looks good now!

2024-01-22 00:10 UTC, ThatMegamind approved these changes
Looks good to us!

2024-01-22 00:10 UTC, merged