implemented auth [unfinished]
ctc-uci/aiss-frontend pull request #5
Opened 2023-11-29 23:32 UTC by kristenyee

closes #3

2023-11-29 23:33 UTC, ctc-devops commented on src/components/Login.jsx
> +const Login = ({ cookies }) => {
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh only works when a file only exports components. Move your component(s) to a separate file.

2023-11-29 23:33 UTC, ctc-devops commented on src/components/Login.jsx
> +export default withCookies(Login);
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh can't handle anonymous components. Add a name to your export.

2023-11-29 23:33 UTC, ctc-devops commented on src/components/Logout.jsx
> +const Logout = ({ cookies }) => {
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh only works when a file only exports components. Move your component(s) to a separate file.

2023-11-29 23:33 UTC, ctc-devops commented on src/components/Logout.jsx
> +export default withCookies(Logout);
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh can't handle anonymous components. Add a name to your export.

2023-11-29 23:33 UTC, ctc-devops commented on src/utils/ProtectedRoute.jsx
> +const ProtectedRoute = ({ Component, redirectPath, roles, cookies }) => {
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh only works when a file only exports components. Move your component(s) to a separate file.

2023-11-29 23:33 UTC, ctc-devops commented on src/utils/ProtectedRoute.jsx
> +export default withCookies(ProtectedRoute);
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh can't handle anonymous components. Add a name to your export.

2023-12-20 22:47 UTC, michellelin1 requested changes
overall, everything functionally works! we just have a few minor comments below. and could you also move all the new components you made to a folder called `Authentication`? after that you're good to merge :)

2023-12-20 22:47 UTC, michellelin1 commented on src/App.jsx
> +    </ChakraProvider> */}
could you put all the new code inside `ChakraProvider`? that way in the future we can style with chakraUI

2023-12-20 22:47 UTC, michellelin1 commented on src/App.jsx
> +            {/* <Route exact path="/dashboard" element={<Dashboard />} /> */}
please remove this comment

2023-12-27 00:52 UTC, ctc-devops commented on src/components/Authentication/Login.jsx
> +const Login = ({ cookies }) => {
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh only works when a file only exports components. Move your component(s) to a separate file.

2023-12-27 00:52 UTC, ctc-devops commented on src/components/Authentication/Login.jsx
> +export default withCookies(Login);
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh can't handle anonymous components. Add a name to your export.

2023-12-27 00:52 UTC, ctc-devops commented on src/components/Authentication/Logout.jsx
> +const Logout = ({ cookies }) => {
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh only works when a file only exports components. Move your component(s) to a separate file.

2023-12-27 00:52 UTC, ctc-devops commented on src/components/Authentication/Logout.jsx
> +export default withCookies(Logout);
⚠️ **[eslint]** <react-refresh/only-export-components> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Fast refresh can't handle anonymous components. Add a name to your export.

2023-12-30 01:03 UTC, michellelin1 approved these changes
lgtm :)

2023-12-30 01:04 UTC, merged